import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Restaurant Management System</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Restaurant Management System</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://raghavkattel.com.np'
          target='_blank'
          rel='noopener noreferrer'>
          Powered by argahv
        </a>
      </footer>
    </div>
  );
};

export default Home;
